name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Gatsby app
        run: npm run build

      - name: Deploy to Firebase Hosting
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
